easy_admin:
  entities:
    Mode:
      class: App\Entity\Mode
      list:
        actions:
          - {name: edit, icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: delete, icon: 'trash', label: false, css_class: 'btn btn-danger'}
