easy_admin:
  entities:
    Verbs:
      class: App\Entity\Verbs
      list:
        actions:
          - {name: edit, icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: delete, icon: 'trash', label: false, css_class: 'btn btn-danger'}
